logging:
  level:
    org.springframework.security: INFO
spring:
  session:
    store-type: redis
server:
  port: ${admin_secret_port:8081}
eureka:
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/